In [2]:
%pip install numpy


[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB 445.2 kB/s eta 0:00:28
   ---------------------------------------- 0.0/12.3 MB 330.3 kB/s eta 0:00:38
   ---------------------------------------- 0.1/12.3 MB 469.7 kB/s eta 0:00:27
   ---------------------------------------- 0.1/12.3 MB 658.7 kB/s eta 0:00:19
    --------------------------------------- 0.2/12.3 MB 655.4 kB/s eta 0:00:19
    --------------------------------------- 0.2/12.3 MB 655.9 kB/s eta 0:00:19
    --------------------------------------- 0.3/12.3 MB 811.7 kB/s eta 0:00:15
   - -------------------------------------- 0.4/12.3 MB 1.1 MB/s eta 0:00:11
   - -------------------------------------- 0.6/12.3 MB 1.3 MB/s eta 0:00:09
   -- ------------------------------------- 0.7/12.3 MB 1.5 MB/s eta 0:00:08
   -- 

In [1]:
# From Python Lists
import numpy as np
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
 
# Special Arrays
np.zeros((3, 3))
np.ones((2, 4))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)


array([[-0.27365916, -0.13434621],
       [-0.05252066,  0.15888861],
       [ 1.58490163,  0.86245813]])

In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(2, 3)
2
6
int64


In [ ]:
# Basic Math

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)
 
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B
 
# Aggregation
arr = np.array([1, 2, 3, 4])
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()


np.float64(1.118033988749895)

In [ ]:


arr = np.array([1, 2, 3, 4, 5])
arr[0]
arr[1:4]
arr[::2]
 
# 2D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]
arr[:, 1]
arr[1, :2]
 
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]


array([4, 5])

In [ ]:
# Reshape

arr = np.arange(6)
arr.reshape(2, 3)
 
# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))
 
# Stacking
np.vstack((a, b))
np.hstack((a, b))


array([1, 2, 3, 4])

In [ ]:

a = np.array([1, 2, 3])
a + 5  # [6, 7, 8]


array([6, 7, 8])

In [ ]:

    # Save to a file
np.save('array.npy', arr)
 
# Load from a file
loaded_arr = np.load('array.npy')

